version: "3.5"
services:
    nginx:
        build:
            context: .
            dockerfile: nginx/Dockerfile
        restart: on-failure
        ports:
            - "80:80"
        depends_on:
            - php

    php:
        build:
            context: .
            dockerfile: php/Dockerfile
        restart: on-failure
        volumes:
            - ./php/public:/var/www/html/public
