version: "3.5"
services:
    nginx:
        build:
            context: .
            dockerfile: nginx/Dockerfile
        restart: on-failure
        ports:
            - "80:80"
        depends_on:
            - php
        volumes:
            - ./nginx/public:/var/www/html/public

    php:
        build:
            context: .
            dockerfile: php/Dockerfile
        restart: on-failure
        volumes:
            - ./php/public:/var/www/html/public

    mysql:
        build:
            context: .
            dockerfile: mysql/Dockerfile
        restart: on-failure
        volumes:
            - dbvol:/var/lib/mysql
            #dbvol to wolumen stworzony przez dokera
        #   - ./mysql/docker-mysql-dir:/var/lib/mysql
        # przed : to moja maszyna  a po : to katalog w kontenerze mysqla
        # 2 linijki powy żej były tylko po to zeby po utworzeniu  utrwalic foder na dysku, zeby  nie musiał tworzyc go przy każdym uruchamianiu kontenera ALE coś na moim dokerze pod Windowsem 7 nie chciało to działać i kontener mysql sie cały czas restartował
        #standardowo tworzy połączenie na porcie 3306 !!!
        environment:
            - MYSQL_ROOT_PASSWORD=mypass
        command: --default-authentication-plugin=mysql_native_password
        #&& sh -c "mysql -uroot -pmypass < /baza/start.sql"
        #linijka powyżej - próbowalismy naprawić utrwalanie folderu na dysku ALE dalej nie działa
        
volumes:
    dbvol:
#a tu deklarujemy ten wolumen dokerowy